# ip: 192.168.0.150
# port: 1001
# force: 35
# protocol: tcp
# local_port: 1501
# com_mode: script
# rate: 10
# force: 35
# home_at_start: false

ip: 192.168.0.150
port: 1001
force: 35
protocol: tcp
local_port: 1501
com_mode: polling
rate: 30
force: 35
home_at_start: false