point_cloud_topics:
  [
    "/d455_0/camera/depth/color/points",
    "/d455_1/camera/depth/color/points",
    "/d405/camera/depth/color/points",
  ]
filtered_points_topic: "/filtered_points"

## ICP for final alignment
icp_enabled: true
max_correspondence_distance: 0.01
transformation_epsilon: 0.000000001
fitness_epsilon: 1
max_iterations: 10
ransac_rejection_threshold: 0.05

## Filters
# voxel filter
voxel_enabled: true
leaf_sizes:
  - [0.001, 0.001, 0.001]
  - [0.001, 0.001, 0.001]
  - [0.001, 0.001, 0.001]

# Box Filter
box_enabled: true

# only cylinder
# box_min: [0.42, -0.127, 0]
# box_max: [0.46, -0.075, 0.05]

# entire box
box_min: [0.2, -0.4064, -0.01]
box_max: [0.9398, 0.4064, 0.20]

# Outlier filter
outlier_mean: 10
outlier_stddev: 5
