point_cloud_topics:
  [
    "d455_0/camera/aligned_depth_to_color/color/masked_points",
    "d455_0/camera/aligned_depth_to_color/color/masked_points",
    "d455_0/camera/aligned_depth_to_color/color/masked_points",
  ]
filtered_points_topic: "filtered_object_points"


## ICP for final alignment
icp_enabled: false 
max_correspondence_distance: 0.01
transformation_epsilon: 0.000000001
fitness_epsilon: 1
max_iterations: 20
ransac_rejection_threshold: 0.05

## Filters

median_enabled: false
# voxel filter
voxel_enabled: false
leaf_sizes:
  - [0.0001, 0.0001, 0.001]
  - [0.0001, 0.0001, 0.001]
  - [0.0001, 0.0001, 0.001]

# Box Filter
box_enabled: false

# only cylinder
# box_min: [0.42, -0.127, 0]
# box_max: [0.46, -0.075, 0.05]

# entire box
box_min: [0.2, -0.4064, -0.01]
box_max: [0.9398, 0.4064, 0.20]

# Outlier filter
outlier_mean: 10
outlier_stddev: 5
