# mesh paths as params
# square_peg: $(find nist_board_gazebo)/models/mesh/KET8-1.STL
# large_round_peg: $(find nist_board_gazebo)/models/mesh/RGOCG16-50_16mm-1.STL
# bolt_rack: $(find nist_board_gazebo)/models/mesh/bolt_rack-1.STL
# plate: $(find nist_board_gazebo)/models/mesh/ICRA2022_Practice_Base-1.STL
cable_female: $(find nist_board_gazebo)/models/cable-connector-female/1.pcd
cable_male: $(find nist_board_gazebo)/models/cable-connector-male/1.pcd